$years = @('2566', '2567', '2568', '2569', '2570')
$sqlHeader = @"
-- =========================================================================
-- SUPABASE DATABASE SETUP SCRIPT FOR STRATEGIC KPI (2566 - 2570)
-- =========================================================================

DROP TABLE IF EXISTS strategic_kpis CASCADE;

CREATE TABLE strategic_kpis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id VARCHAR(50) NOT NULL,
    fiscal_year VARCHAR(10) NOT NULL,
    order_num INT,
    strategy_num INT,
    strategy_name TEXT NOT NULL,
    objective_name TEXT,
    kpi_name TEXT NOT NULL,
    unit VARCHAR(50),
    direction VARCHAR(50) DEFAULT 'ยิ่งมากยิ่งดี',
    baseline TEXT,
    target TEXT,
    actual TEXT,
    status VARCHAR(50),
    responsible_dept TEXT,
    note_revision TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_kpi_year ON strategic_kpis(fiscal_year);
CREATE INDEX idx_kpi_strategy ON strategic_kpis(strategy_num);
CREATE INDEX idx_kpi_code ON strategic_kpis(kpi_id);

ALTER TABLE strategic_kpis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Access" 
ON strategic_kpis FOR SELECT 
USING (true);

CREATE POLICY "Public Update Access" 
ON strategic_kpis FOR UPDATE 
USING (true);

CREATE POLICY "Public Insert Access" 
ON strategic_kpis FOR INSERT 
WITH CHECK (true);

INSERT INTO strategic_kpis 
(kpi_id, fiscal_year, order_num, strategy_num, strategy_name, objective_name, kpi_name, unit, direction, baseline, target, actual, status, responsible_dept, note_revision)
VALUES
"@

$rowList = [System.Collections.Generic.List[string]]::new()

foreach ($y in $years) {
    $csvPath = "d:\AGY\KPI_$y.csv"
    if (Test-Path $csvPath) {
        $lines = [System.IO.File]::ReadAllLines($csvPath, [System.Text.Encoding]::UTF8)
        for ($i = 1; $i -lt $lines.Length; $i++) {
            $line = $lines[$i]
            if ([string]::IsNullOrWhiteSpace($line)) { continue }
            
            $fields = [System.Collections.Generic.List[string]]::new()
            $pattern = '(?<=^|,)(?:\"(?<val>[^\"]*(?:\"\"[^\"]*)*)\"|(?<val>[^,]*))'
            $matches = [regex]::Matches($line, $pattern)
            foreach ($m in $matches) {
                $fields.Add($m.Groups['val'].Value.Replace('""', '"'))
            }

            if ($fields.Count -ge 13) {
                $kpi_id = $fields[0].Replace("'", "''")
                $order_num = if ($fields[1] -match '^\d+$') { $fields[1] } else { 'NULL' }
                $strategy_name = $fields[2].Replace("'", "''")
                $strat_num = 1
                if ($strategy_name -match '(\d+)') {
                    $strat_num = [int]$Matches[1]
                }
                $objective_name = $fields[3].Replace("'", "''")
                $kpi_name = $fields[4].Replace("'", "''")
                $unit = $fields[5].Replace("'", "''")
                $direction = $fields[6].Replace("'", "''")
                $baseline = if ($fields[7]) { "'" + $fields[7].Replace("'", "''") + "'" } else { 'NULL' }
                $target = if ($fields[8]) { "'" + $fields[8].Replace("'", "''") + "'" } else { 'NULL' }
                $actual = if ($fields[9]) { "'" + $fields[9].Replace("'", "''") + "'" } else { 'NULL' }
                $status = if ($fields[10]) { "'" + $fields[10].Replace("'", "''") + "'" } else { 'NULL' }
                $responsible = if ($fields[11]) { "'" + $fields[11].Replace("'", "''") + "'" } else { 'NULL' }
                $notes = if ($fields[12]) { "'" + $fields[12].Replace("'", "''") + "'" } else { 'NULL' }
                
                $rowList.Add("('$kpi_id', '$y', $order_num, $strat_num, '$strategy_name', '$objective_name', '$kpi_name', '$unit', '$direction', $baseline, $target, $actual, $status, $responsible, $notes)")
            }
        }
    }
}

$allSql = $sqlHeader + "`n" + [string]::Join(",`n", $rowList) + ";`n"
[System.IO.File]::WriteAllText('d:\AGY\supabase_schema_and_seed.sql', $allSql, [System.Text.Encoding]::UTF8)
Write-Host "Generated supabase_schema_and_seed.sql successfully with $($rowList.Count) rows!"
